import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import type { EntityKind } from "../../lib/types";
import { isTableLike, normalizeTable, type PlannedAttribute } from "../import/smart-table";
import { fieldsForEntity, fieldsForRelation, type StructuredFieldDefinition } from "../../lib/structured-fields";
import { defaultSpreadFor, defaultsAfterKindChange, hasRelationKindConflict, relationLabelForKind, RELATION_PRESETS, SPREAD_OPTIONS } from "./relation-options";

const kinds: Array<[EntityKind, string]> = [["wechat", "微信号"], ["qq", "QQ号"], ["phone", "手机号"], ["ip", "IP"], ["location", "活跃位置"], ["datacenter", "机房信息"], ["device", "设备"], ["group", "群聊"], ["platform", "平台账号"], ["organization", "个人/团伙"], ["custom", "其他"]];
const kindLabel = (kind: EntityKind) => kinds.find(([value]) => value === kind)?.[1] || "对象";
const valuesFrom = (raw: string) => [...new Set(raw.split(/\r?\n|\t|,|，/).map((value) => value.trim()).filter(Boolean))];
type QuickAddInput = { kind: EntityKind; values: string[]; label: string; spread: string; note: string; customType: string; entityAttributes: PlannedAttribute[]; relationAttributes: PlannedAttribute[] };
type Props = { open: boolean; sourceLabel?: string; initialKind: EntityKind; initialRelationLabel?: string; initialSpread?: string; onClose(): void; onOpenSmartImport(text: string): void; onAdd(input: QuickAddInput): Promise<void>; };
export async function completeQuickAdd(onAdd: Props["onAdd"], input: QuickAddInput, onClose: Props["onClose"], onError: (message: string) => void) { try { await onAdd(input); onClose(); } catch (reason) { onError(`保存失败：${String(reason)}`); } }
export function QuickAddDialog({ open, sourceLabel, initialKind, initialRelationLabel, initialSpread, onClose, onOpenSmartImport, onAdd }: Props) {
  const [raw, setRaw] = useState(""), [kind, setKind] = useState<EntityKind>(initialKind), [label, setLabel] = useState(relationLabelForKind(initialKind)), [labelEdited, setLabelEdited] = useState(false), [spread, setSpread] = useState(defaultSpreadFor(initialKind)), [note, setNote] = useState(""), [customType, setCustomType] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState(""), [more, setMore] = useState(false), [attributes, setAttributes] = useState<Record<string, string>>({});
  const field = useRef<HTMLTextAreaElement>(null), busyRef = useRef(busy), closeRef = useRef(onClose), tableLike = useMemo(() => isTableLike(raw), [raw]), values = useMemo(() => tableLike ? [] : valuesFrom(raw), [raw, tableLike]);
  busyRef.current = busy; closeRef.current = onClose;
  const conflict = hasRelationKindConflict(label, kind);
  const entityFields = fieldsForEntity(kind), relationFields = fieldsForRelation(label);
  const commonFields = [...entityFields.filter((item) => !item.advanced).map((item) => ({ ...item, owner: "entity" as const })), ...relationFields.filter((item) => !item.advanced).map((item) => ({ ...item, owner: "relation" as const }))];
  const advancedFields = [...entityFields.filter((item) => item.advanced).map((item) => ({ ...item, owner: "entity" as const })), ...relationFields.filter((item) => item.advanced).map((item) => ({ ...item, owner: "relation" as const }))];
  useEffect(() => { if (!open) return; setRaw(""); setKind(initialKind); setLabel(initialRelationLabel || relationLabelForKind(initialKind)); setLabelEdited(Boolean(initialRelationLabel)); setSpread(initialSpread || defaultSpreadFor(initialKind)); setNote(""); setCustomType(""); setError(""); setMore(fieldsForEntity(initialKind).some((item)=>!item.advanced)||fieldsForRelation(relationLabelForKind(initialKind)).some((item)=>!item.advanced)); setAttributes({}); const timer = window.setTimeout(() => field.current?.focus(), 0); const escape = (event: KeyboardEvent) => { if (event.key === "Escape" && !busyRef.current) closeRef.current(); }; window.addEventListener("keydown", escape); return () => { window.clearTimeout(timer); window.removeEventListener("keydown", escape); }; }, [open, initialKind, initialRelationLabel, initialSpread]);
  if (!open) return null;
  function routeTable(input: string) { if (busy || !isTableLike(input)) return false; normalizeTable(input); onOpenSmartImport(input); return true; }
  function planned(field: StructuredFieldDefinition): PlannedAttribute[] { const valueText=(attributes[field.key]||"").trim(); if(!valueText)return []; const item:PlannedAttribute={fieldKey:field.key,valueType:field.valueType,valueText}; if(field.valueType==="number"){const valueNumber=Number(valueText.replace("%",""));if(Number.isFinite(valueNumber))item.valueNumber=valueText.includes("%")?valueNumber/100:valueNumber;} if(field.valueType==="datetime")item.valueTime=valueText; return [item]; }
  async function submit(event: FormEvent) { event.preventDefault(); if (routeTable(raw) || !values.length || busy) return; setBusy(true); setError(""); try { const entityAttributes=entityFields.flatMap(planned),relationAttributes=relationFields.flatMap(planned); await completeQuickAdd(onAdd, { kind, values, label: label.trim() || relationLabelForKind(kind), spread, note, customType, entityAttributes, relationAttributes }, onClose, setError); } finally { setBusy(false); } }
  return <div className="modal-backdrop" onClick={() => { if (!busy) onClose(); }}><form className="dialog entry-dialog quick-add-dialog" onSubmit={submit} onClick={(event) => event.stopPropagation()}>
    <header><div><h2>简要录入</h2><p className="entry-sentence">{sourceLabel || "当前对象"} <b>— {label.trim() || "关系"} →</b> {kindLabel(kind)}</p></div><button type="button" onClick={onClose} disabled={busy} aria-label="关闭">×</button></header>
    <div className="entry-scroll-body">
      {error && <p className="field-help" role="alert">{error}</p>}
      <fieldset disabled={busy}><legend>关联对象</legend><label>对象类型<select value={kind} onChange={(event) => { const next = event.target.value as EntityKind, defaults = defaultsAfterKindChange(next, label, labelEdited); setKind(next); setLabel(defaults.label); setSpread(defaults.spread); }}>{kinds.map(([value, text]) => <option value={value} key={value}>{text}</option>)}</select></label><label>对象值<textarea ref={field} value={raw} onPaste={(event) => { const text = event.clipboardData.getData("text"); if (routeTable(text)) event.preventDefault(); }} onChange={(event) => { const text = event.target.value; if (!routeTable(text)) setRaw(text); }} placeholder="输入或粘贴多个值；每行、Tab 或逗号分隔" required /></label><div className="quick-add-status">{values.length ? `将添加 ${values.length} 条关联` : "可一次粘贴多条"}</div></fieldset>
      <fieldset disabled={busy}><legend>关系</legend><label>关系名称<input list="quick-relation-presets" value={label} onChange={(event) => { setLabel(event.target.value); setLabelEdited(true); }} placeholder="选择常用关系或直接输入" required /></label><datalist id="quick-relation-presets">{RELATION_PRESETS.map((preset) => <option value={preset} key={preset} />)}</datalist><div className="relation-recommendations" aria-label="常用关系">{RELATION_PRESETS.map((preset) => <button type="button" key={preset} className={label === preset ? "selected" : ""} onClick={() => { setLabel(preset); setLabelEdited(true); }}>{preset}</button>)}</div>{conflict && <p className="field-help" role="alert">当前关系与对象类型可能不匹配；仍可保存，或修改关系名称。</p>}</fieldset>
      <details className="advanced-details" open={more} onToggle={(event) => { if (!busy) setMore(event.currentTarget.open); }}><summary onClick={(event) => { if (busy) event.preventDefault(); }}>补充信息</summary><fieldset disabled={busy}>{commonFields.length ? <div className="quick-structured-fields">{commonFields.map((field) => <label key={`${field.owner}:${field.key}`}>{field.label}<small>{field.owner === "entity" ? "对象信息" : "关系信息"}</small><input type={field.valueType === "datetime" ? "datetime-local" : "text"} value={attributes[field.key] || ""} placeholder={field.placeholder} onChange={(event) => setAttributes({ ...attributes, [field.key]: event.target.value })} /></label>)}</div> : <p className="field-help">当前对象和关系没有预设结构化字段。</p>}{advancedFields.length>0&&<details className="template-fields"><summary>更多模板字段</summary>{advancedFields.map((field)=><label key={`${field.owner}:${field.key}`}>{field.label}<small>{field.owner === "entity" ? "对象信息" : "关系信息"}</small><input type={field.valueType === "datetime" ? "datetime-local" : "text"} value={attributes[field.key] || ""} placeholder={field.placeholder} onChange={(event)=>setAttributes({...attributes,[field.key]:event.target.value})}/></label>)}</details>}<label>扩散方式<select value={spread} onChange={(event) => setSpread(event.target.value)}>{SPREAD_OPTIONS.map((item) => <option key={item}>{item}</option>)}</select></label><label>备注 / 研判说明<textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><label>对象类型高级调整<input value={customType} onChange={(event) => setCustomType(event.target.value)} placeholder="可选，自定义类型名称" /></label></fieldset></details>
    </div><footer><button type="button" onClick={onClose} disabled={busy}>取消</button><button className="primary" disabled={!values.length || busy}>{busy ? "正在保存…" : `添加 ${values.length || ""} 条`}</button></footer>
  </form></div>;
}
