import { DragEvent, MouseEvent, useMemo, useState } from "react";
import type { ArchiveFolder, CaseRecord } from "../../lib/types";

interface Props { cases: CaseRecord[]; folders: ArchiveFolder[]; activeId?: string; onOpen(id:string):void; onReorder(ids:string[]):void; onCreate():void; onArchive(item:CaseRecord):void; onRestore(item:CaseRecord):void; onTrash(item:CaseRecord):void; onDelete(item:CaseRecord):void; onManageFolders():void; }
const STORAGE_KEY="clue-workbench.sidebar-open";
function initialOpen(){try{const value=localStorage.getItem(STORAGE_KEY);return value?new Set<string>(JSON.parse(value)):new Set<string>(["archive-root"])}catch{return new Set<string>(["archive-root"])}}

export function CaseSidebar(props: Props) {
  const [menu,setMenu]=useState<{item:CaseRecord;x:number;y:number}|null>(null),[dragged,setDragged]=useState<string|null>(null),[open,setOpen]=useState<Set<string>>(initialOpen);
  const active=useMemo(()=>props.cases.filter(x=>x.status==="active").sort((a,b)=>a.sortOrder-b.sortOrder),[props.cases]);
  const archived=useMemo(()=>props.cases.filter(x=>x.status==="archived").sort((a,b)=>a.sortOrder-b.sortOrder),[props.cases]);
  const trash=useMemo(()=>props.cases.filter(x=>x.status==="trash").sort((a,b)=>a.sortOrder-b.sortOrder),[props.cases]);
  const toggle=(key:string)=>setOpen(current=>{const next=new Set(current);next.has(key)?next.delete(key):next.add(key);try{localStorage.setItem(STORAGE_KEY,JSON.stringify([...next]))}catch{}return next});
  const openMenu=(event:MouseEvent,item:CaseRecord)=>{event.preventDefault();setMenu({item,x:event.clientX,y:event.clientY})};
  const dropOn=(event:DragEvent,targetId:string)=>{event.preventDefault();if(!dragged||dragged===targetId)return;const list=active.map(x=>x.id),from=list.indexOf(dragged),to=list.indexOf(targetId);if(from<0||to<0)return;list.splice(to,0,list.splice(from,1)[0]);props.onReorder(list);setDragged(null)};
  const action=(callback:(item:CaseRecord)=>void)=>{if(menu)callback(menu.item);setMenu(null)};
  const rootOpen=open.has("archive-root"),trashOpen=open.has("trash");
  return <aside className="case-sidebar" onClick={()=>setMenu(null)}><header className="product-mark"><span className="mark-dot"/><div><strong>线索研判</strong><small>本地案件工作台</small></div></header><div className="sidebar-heading"><span>案件库</span><button type="button" className="new-case-button" onClick={props.onCreate}><b>＋</b>新建</button></div><section className="case-section">{active.map(item=><CaseRow key={item.id} item={item} selected={item.id===props.activeId} draggable onOpen={props.onOpen} onContext={openMenu} onDragStart={setDragged} onDragOver={dropOn}/>)}</section>
  <section className="case-section archive-root"><span><button className="section-toggle" onClick={()=>toggle("archive-root")}>{rootOpen?"⌄":"›"} 归档</button><button className="manage-folders" onClick={props.onManageFolders} aria-label="管理归档文件夹">管理</button></span>{rootOpen&&<>{props.folders.map(folder=>{const items=archived.filter(x=>x.archiveFolderId===folder.id),key=`folder:${folder.id}`,opened=open.has(key);return <div className="archive-folder" key={folder.id}><button className="folder-toggle" onClick={()=>toggle(key)}><span>{opened?"⌄":"›"} {folder.name}</span><small>{items.length}</small></button>{opened&&items.map(item=><CaseRow key={item.id} item={item} selected={item.id===props.activeId} onOpen={props.onOpen} onContext={openMenu}/>)}</div>})}<ArchiveGroup name="未分类" storageKey="uncategorized" items={archived.filter(x=>!x.archiveFolderId)} open={open} toggle={toggle} activeId={props.activeId} onOpen={props.onOpen} onContext={openMenu}/></>}</section>
  <section className="case-section muted-section archive-folder"><button className="folder-toggle" onClick={()=>toggle("trash")}><span>{trashOpen?"⌄":"›"} 回收站</span><small>{trash.length}</small></button>{trashOpen&&trash.map(item=><CaseRow key={item.id} item={item} selected={item.id===props.activeId} onOpen={props.onOpen} onContext={openMenu}/>)}</section><footer><span>案件均保存在本机</span></footer>
  {menu&&<div className="context-menu" style={{left:menu.x,top:menu.y}} onClick={e=>e.stopPropagation()}><button onClick={()=>{props.onOpen(menu.item.id);setMenu(null)}}>打开</button>{menu.item.status==="active"&&<button onClick={()=>action(props.onArchive)}>归档…</button>}{menu.item.status==="archived"&&<><button onClick={()=>action(props.onArchive)}>修改归档…</button><button onClick={()=>action(props.onRestore)}>恢复到进行中</button></>}<button onClick={()=>action(props.onTrash)}>移到回收站</button>{menu.item.status==="trash"&&<button className="danger" onClick={()=>action(props.onDelete)}>永久删除…</button>}</div>}</aside>;
}
function ArchiveGroup({name,storageKey,items,open,toggle,activeId,onOpen,onContext}:{name:string;storageKey:string;items:CaseRecord[];open:Set<string>;toggle(k:string):void;activeId?:string;onOpen(id:string):void;onContext(e:MouseEvent,item:CaseRecord):void}){const key=`folder:${storageKey}`,opened=open.has(key);return <div className="archive-folder"><button className="folder-toggle" onClick={()=>toggle(key)}><span>{opened?"⌄":"›"} {name}</span><small>{items.length}</small></button>{opened&&items.map(item=><CaseRow key={item.id} item={item} selected={item.id===activeId} onOpen={onOpen} onContext={onContext}/>)}</div>}
function CaseRow({item,selected,draggable,onOpen,onContext,onDragStart,onDragOver}:{item:CaseRecord;selected:boolean;draggable?:boolean;onOpen(id:string):void;onContext(e:MouseEvent,item:CaseRecord):void;onDragStart?:(id:string)=>void;onDragOver?:(e:DragEvent,id:string)=>void}){return <button className={`case-row ${selected?"selected":""}`} draggable={draggable} onDragStart={()=>onDragStart?.(item.id)} onDragOver={e=>onDragOver?.(e,item.id)} onClick={()=>onOpen(item.id)} onContextMenu={e=>onContext(e,item)}><strong>{item.archiveTitle||item.title}</strong><small>{item.status==="trash"?"已移入回收站":`${item.entityCount} 节点 · ${item.relationCount} 关系`} · {item.updatedAt}</small></button>}
