import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { open as pickPath } from "@tauri-apps/plugin-dialog";
import "./styles/app.css";
import { CaseSidebar } from "./features/cases/CaseSidebar";
import { ArchiveFolderDialog } from "./features/cases/ArchiveFolderDialog";
import { AttachmentPanel } from "./features/cases/AttachmentPanel";
import { CaseOverviewDialog } from "./features/cases/CaseOverviewDialog";
import { CreateCaseDialog } from "./features/cases/CreateCaseDialog";
import { confirmPermanentCaseDeletion } from "./features/cases/permanent-delete";
import { ExportPanel } from "./features/export/ExportPanel";
import { GraphPanel } from "./features/graph/GraphPanel";
import { QuickAddDialog } from "./features/graph/QuickAddDialog";
import { QuickEntryPanel, type QuickEntryPreset } from "./features/graph/QuickEntryPanel";
import { StructuredAttributeEditor } from "./features/graph/StructuredAttributeEditor";
import { ImportDialog } from "./features/import/ImportDialog";
import type { ImportPlan, PlannedRelation } from "./features/import/smart-table";
import { attributeLabel, attributeValue } from "./lib/entity-presentation";
import { addAttachment, addRelations, archiveCase, createArchiveFolder, createCase, deleteArchiveFolder, deleteAttachment, deleteAttribute, deleteEntity, exportCaseTo, getCaseDetail, getExternalRevision, importCasePackage, importPlan, initializeStorage, listArchiveFolders, listCases, listImportBatches, openAttachment, permanentlyDeleteCase, redoCase, renameArchiveFolder, reorderCases, restoreCase, trashCase, undoCase, undoImportBatch, updateAttachmentNote, updateCaseOverview, updateEntity, updateRelation, upsertAttributes } from "./lib/desktop-api";
import { kindLabel, type ArchiveFolder, type AttributeRecord, type CaseDetail, type CaseRecord, type EntityKind, type ExportResult, type ImportBatch } from "./lib/types";

type Dialog = "create" | "archive" | "add" | "entity" | "relation" | "case" | "import" | "folders" | null;
const displayNamePresets = ["生活号", "业务号", "小号", "未确定账号", "被盗账号"];
const formatAttribute = (attribute: AttributeRecord) => attribute.fieldKey === "similarity" && attribute.valueType === "number" && attribute.valueNumber != null ? `${Math.round(attribute.valueNumber * 1000) / 10}%` : attributeValue(attribute);
const withCurrentOption = (options: string[], current: string) => [...new Set([current, ...options])].map(value => ({ value, label: value || "未设置" }));

export default function App() {
  const [cases, setCases] = useState<CaseRecord[]>([]), [folders, setFolders] = useState<ArchiveFolder[]>([]);
  const [folderError, setFolderError] = useState("");
  const [detail, setDetail] = useState<CaseDetail>(), [batches, setBatches] = useState<ImportBatch[]>([]);
  const [activeId, setActiveId] = useState<string>(), [selectedId, setSelectedId] = useState<string>(), [relationId, setRelationId] = useState<string>();
  const [dialog, setDialog] = useState<Dialog>(null), [target, setTarget] = useState<CaseRecord>(), [exportResult, setExportResult] = useState<ExportResult | null>(null);
  const [message, setMessage] = useState("正在打开本地案件库…"), [historyPending, setHistoryPending] = useState(false);
  const [storage, setStorage] = useState<Awaited<ReturnType<typeof initializeStorage>> | null>(null);
  const [query, setQuery] = useState(""), [palette, setPalette] = useState(false), [addPreset, setAddPreset] = useState<QuickEntryPreset>({ kind: "qq" });
  const [entityDisplayName, setEntityDisplayName] = useState(""), [smartImportText, setSmartImportText] = useState("");
  const externalRevision = useRef<string>(), refreshSequence = useRef(0), activeCaseId = useRef<string>();
  const selected = useMemo(() => detail?.entities.find(item => item.id === selectedId), [detail, selectedId]);
  const selectedRelation = useMemo(() => detail?.relations.find(item => item.id === relationId), [detail, relationId]);
  const selectedAttributes = useMemo(() => detail?.entityAttributes?.filter(item => item.subjectId === selectedId) || [], [detail, selectedId]);
  const selectedRelationAttributes = useMemo(() => detail?.relationAttributes?.filter(item => item.subjectId === relationId) || [], [detail, relationId]);
  const visibleCases = useMemo(() => { const term=query.trim().toLowerCase(); return term ? cases.filter(item => `${item.title} ${item.archiveTitle || ""} ${item.background}`.toLowerCase().includes(term)) : cases; }, [cases, query]);

  async function refresh(id = activeId) {
    const request = ++refreshSequence.current;
    const [rows, nextFolders] = await Promise.all([listCases(), listArchiveFolders()]);
    if (request !== refreshSequence.current) return;
    const next = id && rows.some(item => item.id === id) ? id : rows.find(item => item.status === "active")?.id || rows[0]?.id;
    if (next !== activeCaseId.current) setExportResult(null);
    activeCaseId.current = next; setCases(rows); setFolders(nextFolders); setActiveId(next);
    if (next) {
      const [nextDetail, nextBatches] = await Promise.all([getCaseDetail(next), listImportBatches(next)]);
      if (request !== refreshSequence.current || activeCaseId.current !== next) return;
      setDetail(nextDetail); setBatches(nextBatches); setSelectedId(current => nextDetail.entities.some(item => item.id === current) ? current : nextDetail.rootId); setRelationId(undefined);
    } else if (request === refreshSequence.current) { setDetail(undefined); setBatches([]); setSelectedId(undefined); setRelationId(undefined); }
  }

  useEffect(() => { let cancelled=false; const timer=window.setTimeout(()=>{if(!cancelled)setMessage("正在等待本地案件库响应…");},3000); void (async()=>{try{setStorage(await initializeStorage());await refresh();externalRevision.current=await getExternalRevision();setMessage("本地案件库已就绪");}catch(error){console.error("初始化失败",error);setMessage(`初始化失败：${String(error)}`);}finally{cancelled=true;window.clearTimeout(timer);}})(); return()=>{cancelled=true;window.clearTimeout(timer);}; }, []);
  useEffect(() => { let cancelled=false; const poll=async()=>{try{const revision=await getExternalRevision();if(!cancelled&&externalRevision.current&&revision!==externalRevision.current){await refresh(activeId);setMessage("已同步命令接口写入的案件变更");}externalRevision.current=revision;}catch{}};const timer=window.setInterval(()=>void poll(),2000);return()=>{cancelled=true;window.clearInterval(timer);};},[activeId]);
  useEffect(() => { const key=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null;const editing=Boolean(target?.closest('input,textarea,select,[contenteditable="true"]'));if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();setPalette(true);return;}if(event.key==="Escape"){setPalette(false);if(!dialog)setQuery("");return;}if(!editing){if(event.key.toLowerCase()==="a"&&!event.metaKey&&!event.ctrlKey&&selected){event.preventDefault();open("add");}else if(event.key.toLowerCase()==="e"&&!event.metaKey&&!event.ctrlKey&&selected){event.preventDefault();open("entity");}else if((event.key==="Backspace"||event.key==="Delete")&&selected&&detail&&selected.id!==detail.rootId){event.preventDefault();void doDeleteNode(selected.id);}}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[selected,detail,dialog]);

  async function run(action:()=>Promise<unknown>){try{await action();await refresh();setMessage("已保存到当前案件");}catch(error){setMessage(`操作未完成：${String(error)}`);}}
  function open(next:Dialog, item?:CaseRecord, preset?:Exclude<EntityKind,"subject">|QuickEntryPreset){setTarget(item);if(next==="add")setAddPreset(typeof preset==="string"?{kind:preset}:preset||{kind:"qq"});if(next==="import")setSmartImportText("");if(next==="entity")setEntityDisplayName(selected?.displayName||"");setDialog(next);}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);try{
    if(dialog==="archive"&&target){let folderId=String(data.get("folderId")||"")||null;if(folderId==="__new__")folderId=(await createArchiveFolder(String(data.get("newFolder")||""))).id;await archiveCase(target.id,String(data.get("archiveTitle")||target.title),String(data.get("note")||""),folderId);}
    if(dialog==="entity"&&selected)await updateEntity({...selected,displayName:String(data.get("displayName")||""),status:String(data.get("status")??selected.status),role:String(data.get("role")??selected.role),note:String(data.get("note")??selected.note),accent:String(data.get("accent")??selected.accent),pinned:data.has("pinned")?data.get("pinned")==="true":selected.pinned});
    if(dialog==="relation"&&selectedRelation){const label=String(data.get("label")??selectedRelation.label).trim();if(!label)throw new Error("关系名称不能为空");await updateRelation({...selectedRelation,label,status:String(data.get("status")??selectedRelation.status),spread:String(data.get("spread")??selectedRelation.spread),note:String(data.get("note")??selectedRelation.note),emphasis:data.has("emphasis")?data.get("emphasis")==="true":selectedRelation.emphasis});}
    await refresh();setDialog(null);
  }catch(error){setMessage(`操作未完成：${String(error)}`);}}
  async function doExport(){if(!detail)return;try{const destination=await pickPath({directory:true,multiple:false,title:"选择案件材料保存位置"});if(!destination||Array.isArray(destination))return;const result=await exportCaseTo(detail.case.id,destination);setExportResult(result);setMessage(`已导出案件材料三件套：${result.packagePath}、${result.xmindPath}、${result.markdownPath}`);}catch(error){setMessage(`导出失败：${String(error)}`);}}
  async function doImportPackage(){try{const path=await pickPath({multiple:false,title:"选择 .cluecase 案件包",filters:[{name:"完整案件包（推荐）",extensions:["cluecase"]},{name:"旧版图谱包（不含附件）",extensions:["json"]}]});if(!path||Array.isArray(path))return;const record=await importCasePackage(path);await refresh(record.id);setMessage(`已导入案件包「${record.title}」${String(path).endsWith(".json")?"；旧版包仅含图谱，不含附件。":""}`);}catch(error){setMessage(`打开案件包失败：${String(error)}`);}}
  async function doDeleteNode(id:string){if(detail&&window.confirm("确认删除此对象？关联关系也会一并删除；删除后可使用撤销恢复。")){try{await deleteEntity(detail.case.id,id);await refresh(detail.case.id);setMessage("对象及其关联已删除，可用撤销恢复");}catch(error){setMessage(`删除未完成：${String(error)}`);}}}
  async function saveAttribute(kind:"entity"|"relation",attribute:AttributeRecord){if(detail){try{await upsertAttributes(detail.case.id,kind,[attribute]);await refresh(detail.case.id);setMessage("结构化属性已保存");}catch(error){setMessage(`结构化属性保存失败：${String(error)}`);}}}
  async function removeAttribute(kind:"entity"|"relation",attribute:AttributeRecord){if(detail){try{await deleteAttribute(detail.case.id,kind,attribute.id);await refresh(detail.case.id);setMessage("结构化属性已删除");}catch(error){setMessage(`结构化属性删除失败：${String(error)}`);}}}
  async function copyAttribute(value:string){try{await navigator.clipboard.writeText(value);setMessage("属性值已复制");}catch{setMessage("复制失败，请手动选择属性值");}}
  async function history(direction:"undo"|"redo"){if(!detail||historyPending)return;setHistoryPending(true);try{const result=await(direction==="undo"?undoCase(detail.case.id):redoCase(detail.case.id));await refresh(detail.case.id);setMessage(`${direction==="undo"?"撤销":"重做"}完成：恢复 ${result.entityCount} 个对象、${result.relationCount} 条关系`);}catch(error){setMessage(`${direction==="undo"?"撤销":"重做"}未完成：${String(error)}`);}finally{setHistoryPending(false);}}
  return <main className="desktop-app"><div className="command-strip"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索案件、背景…" aria-label="搜索案件"/><button onClick={()=>setPalette(true)}>⌘K 命令</button></div>
    <CaseSidebar cases={visibleCases} folders={folders} activeId={activeId} onOpen={id=>void refresh(id)} onReorder={ids=>void run(()=>reorderCases(ids))} onCreate={()=>{setMessage("新建案件：输入案件名和第一条线索即可");open("create");}} onArchive={item=>open("archive",item)} onRestore={item=>void run(()=>restoreCase(item.id))} onTrash={item=>void run(()=>trashCase(item.id))} onDelete={item=>void run(()=>confirmPermanentCaseDeletion(item, permanentlyDeleteCase))} onManageFolders={()=>{setFolderError("");setDialog("folders");}}/>
    <section className="workspace"><header className="app-header"><div className="case-title"><h1>{detail?.case.archiveTitle||detail?.case.title||"没有案件"}</h1><span>{detail?`${detail.entities.length} 个对象 · ${detail.relations.length} 条关系`:"选择案件开始"}</span></div><div className="header-tools"><button disabled={!detail} onClick={()=>open("case")}>案件概览</button><button disabled={!detail||historyPending} onClick={()=>void history("undo")}>{historyPending?"处理中…":"撤销"}</button><button disabled={!detail||historyPending} onClick={()=>void history("redo")}>{historyPending?"处理中…":"重做"}</button></div></header><GraphPanel detail={detail} selectedId={selectedId} selectedRelationId={relationId} onSelect={id=>{setSelectedId(id);setRelationId(undefined);}} onRelation={id=>{setSelectedId(undefined);setRelationId(id);}} onEditRelation={id=>{setSelectedId(undefined);setRelationId(id);setDialog("relation");}} onEditNode={id=>{const entity=detail?.entities.find(item=>item.id===id);setSelectedId(id);setRelationId(undefined);setEntityDisplayName(entity?.displayName||"");setDialog("entity");}} onAddFromNode={id=>{setSelectedId(id);setRelationId(undefined);open("add");}} onDeleteNode={id=>void doDeleteNode(id)}/></section>
    <aside className="inspector"><QuickEntryPanel selected={selected} onOpen={preset=>open("add",undefined,preset)} onImport={()=>open("import")}/><section className="entity-inspector"><span className="eyebrow">{selectedRelation?"当前关系":"当前对象"}</span>{selectedRelation?<><h2>{selectedRelation.label}</h2><p>{detail?.entities.find(item=>item.id===selectedRelation.sourceId)?.displayName||detail?.entities.find(item=>item.id===selectedRelation.sourceId)?.label} → {detail?.entities.find(item=>item.id===selectedRelation.targetId)?.displayName||detail?.entities.find(item=>item.id===selectedRelation.targetId)?.label}</p><AttributeSummary attributes={selectedRelationAttributes} onCopy={copyAttribute}/><section className="note"><strong>备注 / 研判说明</strong><p>{selectedRelation.note||"暂无备注"}</p></section><button onClick={()=>setDialog("relation")}>编辑关系</button></>:<><span className="eyebrow">当前对象</span><h2>{selected?.displayName||selected?.label||"选择图节点"}</h2><p>{selected?`${kindLabel[selected.kind]} · ${selected.label} · ${selected.role} · ${selected.status}`:"右键节点可编辑，或在此查看对象信息"}</p>{selected&&<section className="note"><strong>备注</strong><p>{selected.note||"暂无备注"}</p></section>}{selected&&<details className="advanced-details"><summary>更多信息</summary>{selectedAttributes.filter(item=>formatAttribute(item).trim()).length?selectedAttributes.filter(item=>formatAttribute(item).trim()).map(item=><p key={item.id}><strong>{attributeLabel(item.fieldKey)}</strong>：{formatAttribute(item)}</p>):<p>暂无属性</p>}</details>}</>}</section>
      <AttachmentPanel detail={detail} onAdd={async(sourcePath,note,entityId)=>{if(!detail)return;await addAttachment(detail.case.id,sourcePath,note,entityId);await refresh(detail.case.id);setMessage("附件已固定到当前案件");}} onNote={async(attachment,note)=>{await updateAttachmentNote(attachment.caseId,attachment.id,note);await refresh(attachment.caseId);setMessage("附件说明已保存");}} onDelete={async attachment=>{await deleteAttachment(attachment.caseId,attachment.id);await refresh(attachment.caseId);setMessage("附件及其本地副本已删除");}} onOpen={async attachment=>{await openAttachment(attachment.caseId,attachment.id);setMessage(`已打开附件：${attachment.originalName}`);}}/><ExportPanel disabled={!detail} onExport={()=>void doExport()} onImport={()=>void doImportPackage()} result={exportResult}/></aside>
    {dialog!=="folders"&&dialog!=="case"&&dialog!=="import"&&dialog!=="create"&&dialog!=="add"&&dialog&&(dialog!=="entity"||selected)&&(dialog!=="relation"||selectedRelation)&&<div className="modal-backdrop"><form className="dialog" onSubmit={submit}><header><h2>{dialog==="archive"?"归档案件":dialog==="entity"?"编辑对象":"编辑关系链"}</h2><button type="button" onClick={()=>setDialog(null)}>×</button></header>
      {dialog==="archive"&&<><p>归档会保留全部图、关系和导出历史。</p><label>归档显示名<input name="archiveTitle" defaultValue={target?.archiveTitle||target?.title||""} required/></label><label>归档文件夹<select name="folderId" defaultValue={target?.archiveFolderId||""}><option value="">未分类</option>{folders.map(folder=><option key={folder.id} value={folder.id}>{folder.name}</option>)}<option value="__new__">＋ 新建文件夹</option></select></label><label>新文件夹名称（选择“新建”时填写）<input name="newFolder" placeholder="例如：2026年案件"/></label><label>归档说明<textarea name="note"/></label></>}
      {dialog==="entity"&&selected&&<><label>账号命名 / 显示别名<input name="displayName" value={entityDisplayName} onChange={event=>setEntityDisplayName(event.target.value)} placeholder="例如：团伙联络号、生活号 A"/><span className="display-name-presets"><span className="display-name-presets-label">快速设为</span><span className="display-name-presets-segments" role="group" aria-label="显示别名快捷选项">{displayNamePresets.map(preset=><button type="button" key={preset} className={entityDisplayName===preset?"selected":""} aria-pressed={entityDisplayName===preset} onClick={()=>setEntityDisplayName(preset)}>{preset}</button>)}</span></span></label><div className="row"><label>状态<select name="status" defaultValue={selected.status}>{withCurrentOption(["有效","待核实","已失效","已排除"],selected.status).map(option=><option value={option.value} key={option.value||"__empty_status"}>{option.label}</option>)}</select></label><label>角色<select name="role" defaultValue={selected.role}>{withCurrentOption(["未标注","业务号","生活号","小号","核心账号","扩散节点"],selected.role).map(option=><option value={option.value} key={option.value||"__empty_role"}>{option.label}</option>)}</select></label></div><div className="row"><label>重点颜色<input type="color" name="accent" defaultValue={selected.accent||"#286082"}/></label><label>画布强调<select name="pinned" defaultValue={String(selected.pinned)}><option value="false">普通显示</option><option value="true">标为重点</option></select></label></div><label>备注<textarea name="note" defaultValue={selected.note}/></label><StructuredAttributeEditor attributes={selectedAttributes} onSave={attribute=>saveAttribute("entity",attribute)} onDelete={attribute=>removeAttribute("entity",attribute)}/></>}
      {dialog==="relation"&&selectedRelation&&<><label>关系名称<input name="label" defaultValue={selectedRelation.label} required/></label><StructuredAttributeEditor attributes={selectedRelationAttributes} onSave={attribute=>saveAttribute("relation",attribute)} onDelete={attribute=>removeAttribute("relation",attribute)}/><div className="row"><label>状态<select name="status" defaultValue={selectedRelation.status}><option>有效</option><option>待核实</option><option>已失效</option><option>已排除</option></select></label><label>扩散方式<select name="spread" defaultValue={selectedRelation.spread}><option>账号链扩展</option><option>跨平台映射</option><option>同 IP 扩散</option><option>同机扩散</option><option>群聊扩散</option><option>人工关联</option></select></label></div><label>画布强调<select name="emphasis" defaultValue={String(selectedRelation.emphasis)}><option value="false">普通关系线</option><option value="true">加粗并突出</option></select></label><label>推导说明 / 注意事项<textarea name="note" defaultValue={selectedRelation.note}/></label></>}
      <footer><button type="button" onClick={()=>setDialog(null)}>取消</button><button className="primary">保存</button></footer></form></div>}
    <CreateCaseDialog open={dialog==="create"} onClose={()=>setDialog(null)} onCreate={async input=>{const record=await createCase(input.title,input.background,input.seedKind,input.seedValue);await refresh(record.id);setMessage(`已创建案件「${record.title}」并置顶`);}}/>
    <QuickAddDialog open={dialog==="add"} sourceLabel={selected?.displayName||selected?.label} initialKind={addPreset.kind} initialRelationLabel={addPreset.relationLabel} initialSpread={addPreset.spread} onClose={()=>setDialog(null)} onOpenSmartImport={text=>{setSmartImportText(text);setDialog("import");}} onAdd={async input=>{if(!detail||!selected)throw new Error("请先选择一个当前对象");const outcome=await addRelations(detail.case.id,selected.id,input.kind,input.values,input.label,input.spread,input.note,input.customType,undefined,"快速添加",input.entityAttributes,input.relationAttributes);await refresh(detail.case.id);setMessage(`已添加 ${outcome.addedCount} 条线索${outcome.attributeCount?`，保存 ${outcome.attributeCount} 项属性`:""}`);}}/>
    <CaseOverviewDialog caseRecord={detail?.case} open={dialog==="case"&&Boolean(detail)} onClose={()=>setDialog(null)} onSave={async input=>{if(!detail)return;await updateCaseOverview({id:detail.case.id,...input});await refresh(detail.case.id);setMessage("案件概览已保存");}}/>
    <ImportDialog open={dialog==="import"} initialMode={smartImportText?"smart":"quick"} initialSmartText={smartImportText} initialSource={smartImportText?"快捷录入多列表格":"手工粘贴"} sourceLabel={selected?.displayName||selected?.label} sourceKey={selected?.label} sourceKind={selected?.kind} existingRelations={existingRelations(detail)} existingEntityKeys={new Set(detail?.entities.map(entity=>`${entity.kind}\0${entity.label}`) || [])} onClose={()=>setDialog(null)} onImport={async input=>{if(!detail||!selected)throw new Error("请先选择一个当前对象");const outcome=await addRelations(detail.case.id,selected.id,input.kind,input.values,input.label,input.spread,input.note,input.customType,input.displayNames,input.source);await refresh(detail.case.id);setMessage(outcome.addedCount===0?`已从${input.source}检查：没有新增，候选均已存在`:`已从${input.source}导入：候选 ${outcome.candidateCount}、实际新增 ${outcome.addedCount}、已存在/跳过 ${outcome.skippedCount}`);return outcome;}} onSmartImport={async(plan:ImportPlan,source:string)=>{if(!detail)throw new Error("请先打开案件");const outcome=await importPlan(detail.case.id,plan,source);await refresh(detail.case.id);setMessage(`智能导入完成：新增 ${outcome.addedEntities} 个对象、${outcome.addedRelations} 条关系`);return outcome;}} batches={batches} onUndoBatch={async batch=>{if(!detail)return;const removed=await undoImportBatch(detail.case.id,batch.id);await refresh(detail.case.id);setMessage(`已撤销导入批次：删除 ${removed} 条关系，可用全案撤销恢复`);}}/>
    {palette&&<div className="palette-backdrop" onClick={()=>setPalette(false)}><div className="command-palette" onClick={event=>event.stopPropagation()}><input autoFocus placeholder="输入命令或案件名称" value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={event=>{if(event.key==="Enter"&&visibleCases[0]){void refresh(visibleCases[0].id);setPalette(false);}}}/><div className="palette-section"><button onClick={()=>{open("create");setPalette(false);}}><kbd>N</kbd> 新建案件</button>{selected&&<button onClick={()=>{open("add");setPalette(false);}}><kbd>A</kbd> 为当前对象添加关联</button>}{selected&&<button onClick={()=>{open("entity");setPalette(false);}}><kbd>E</kbd> 编辑当前对象</button>}{detail&&<button onClick={()=>{void doExport();setPalette(false);}}>导出当前案件简报</button>}</div>{visibleCases.length>0&&<div className="palette-results">{visibleCases.slice(0,6).map(item=><button key={item.id} onClick={()=>{void refresh(item.id);setPalette(false);}}>{item.archiveTitle||item.title}<small>{item.entityCount} 节点 · {item.relationCount} 关系</small></button>)}</div>}</div></div>}
    <ArchiveFolderDialog open={dialog==="folders"} folders={folders} cases={cases} error={folderError} onClose={()=>setDialog(null)} onCreate={async name=>{try{await createArchiveFolder(name);setFolders(await listArchiveFolders());setFolderError("");}catch(error){setFolderError(String(error));throw error;}}} onRename={async(id,name)=>{try{await renameArchiveFolder(id,name);await refresh();setFolderError("");}catch(error){setFolderError(String(error));throw error;}}} onDelete={async id=>{try{await deleteArchiveFolder(id);setFolders(await listArchiveFolders());setFolderError("");}catch(error){setFolderError(String(error));throw error;}}}/>
    <div className="status-bar"><span>{message}</span>{storage&&<small>{storage.root}</small>}</div>
  </main>;
}

function AttributeSummary({attributes,onCopy}:{attributes:AttributeRecord[];onCopy(value:string):Promise<void>}) {
  const values=attributes.filter(item=>formatAttribute(item).trim());
  return <section className="readonly-attributes"><strong>关键属性</strong>{values.slice(0,2).map(item=><p key={item.id}><span>{attributeLabel(item.fieldKey)}</span><button type="button" title="复制属性值" onClick={()=>void onCopy(formatAttribute(item))}>{formatAttribute(item)}</button></p>)}{!values.length&&<p>暂无结构化属性</p>}{values.length>2&&<details><summary>展开全部（{values.length}）</summary>{values.slice(2).map(item=><p key={item.id}><span>{attributeLabel(item.fieldKey)}</span><button type="button" title="复制属性值" onClick={()=>void onCopy(formatAttribute(item))}>{formatAttribute(item)}</button></p>)}</details>}</section>;
}

function existingRelations(detail?:CaseDetail):PlannedRelation[]{return (detail?.relations||[]).flatMap(relation=>{const source=detail?.entities.find(entity=>entity.id===relation.sourceId),target=detail?.entities.find(entity=>entity.id===relation.targetId);return source&&target?[{sourceKind:source.kind,sourceKey:source.label,targetKind:target.kind,targetKey:target.label,label:relation.label,attributes:[]}]:[];});}
